export const GET_TOTAL_LIST_REQUEST = 'GET_TOTAL_LIST_REQUEST';
export const GET_TOTAL_LIST_SUCCESS = "GET_TOTAL_LIST_SUCCESS";
export const GET_TOTAL_LIST_FAILURE = "GET_TOTAL_LIST_FAILURE";

export const GET_INFO_FROM_API_REQUEST = 'GET_INFO_FROM_API_REQUEST';
export const GET_INFO_FROM_API_SUCCESS = 'GET_INFO_FROM_API_SUCCESS';
export const GET_INFO_FROM_API_FAILURE = 'GET_INFO_FROM_API_FAILURE';

export const LIST_SLICED = 'LIST_SLICED';

export const LOCAL_STORAGE = 'LOCAL_STORAGE';
